import type { Professional } from "./types";

export function professionalProfileHref(id: string) {
  return `/perfil?profissional=${encodeURIComponent(id)}`;
}

export const professionals: Professional[] = [
  {
    id: "ana",
    name: "Ana Martins",
    role: "Psicóloga",
    initials: "AM",
    tone: "sage",
    specialties: ["Ansiedade", "Trabalho", "Relacionamentos"],
    approach: "Terapia cognitivo-comportamental",
    price: 150,
    rating: "4,9",
    reviews: 127,
    mode: "Online",
    time: "19:00",
    bio: "Um espaço de escuta para acolher sua história e construir, juntos, novas formas de lidar com os desafios do dia a dia.",
  },
  {
    id: "lucas",
    name: "Lucas Almeida",
    role: "Psicólogo",
    initials: "LA",
    tone: "sand",
    specialties: ["Autoestima", "Estresse", "Ansiedade"],
    approach: "Abordagem humanista",
    price: 140,
    rating: "4,8",
    reviews: 98,
    mode: "Online",
    time: "18:00",
    bio: "Acredito no encontro e na escuta sem julgamentos. Meu trabalho valoriza suas experiências e respeita o seu tempo.",
  },
  {
    id: "mariana",
    name: "Mariana Costa",
    role: "Psicóloga",
    initials: "MC",
    tone: "rose",
    specialties: ["Relacionamentos", "Autoestima", "Tristeza"],
    approach: "Psicanálise",
    price: 180,
    rating: "4,9",
    reviews: 84,
    mode: "Online",
    time: "20:00",
    bio: "Vamos abrir espaço para compreender o que você sente, com atenção às suas relações e à singularidade da sua história.",
  },
  {
    id: "rafael",
    name: "Rafael Lima",
    role: "Psicólogo",
    initials: "RL",
    tone: "blue",
    specialties: ["Sono", "Trabalho", "Estresse"],
    approach: "Terapia cognitivo-comportamental",
    price: 160,
    rating: "4,8",
    reviews: 76,
    mode: "Online",
    time: "08:00",
    bio: "Um olhar cuidadoso para sua rotina, seus desafios e as mudanças que você deseja construir.",
  },
  {
    id: "carolina",
    name: "Carolina Alves",
    role: "Psicóloga",
    initials: "CA",
    tone: "sage",
    specialties: ["Ansiedade", "Alimentação", "Autoestima"],
    approach: "Abordagem humanista",
    price: 170,
    rating: "4,9",
    reviews: 63,
    mode: "Presencial em Florianópolis",
    time: "14:00",
    bio: "Ofereço um espaço de acolhimento para explorar sentimentos e desenvolver uma relação mais gentil consigo.",
  },
  {
    id: "beatriz",
    name: "Beatriz Santos",
    role: "Psicóloga",
    initials: "BS",
    tone: "rose",
    specialties: ["Relacionamentos", "Tristeza"],
    approach: "Terapia sistêmica",
    price: 200,
    rating: "4,9",
    reviews: 112,
    mode: "Online",
    time: "17:00",
    bio: "Uma escuta atenta às suas relações, escolhas e possibilidades de mudança.",
  },
  {
    id: "pedro",
    name: "Pedro Oliveira",
    role: "Psicólogo",
    initials: "PO",
    tone: "sand",
    specialties: ["Trabalho", "Ansiedade"],
    approach: "Terapia cognitivo-comportamental",
    price: 130,
    rating: "4,7",
    reviews: 51,
    mode: "Online",
    time: "10:00",
    bio: "Reflexões e caminhos práticos para você cuidar de si, um passo de cada vez.",
  },
  {
    id: "julia",
    name: "Júlia Ferreira",
    role: "Psicóloga",
    initials: "JF",
    tone: "blue",
    specialties: ["Autoestima", "Relacionamentos"],
    approach: "Psicanálise",
    price: 220,
    rating: "4,8",
    reviews: 92,
    mode: "Presencial em Florianópolis",
    time: "18:30",
    bio: "Um convite para olhar para sua história com curiosidade, cuidado e respeito.",
  },
];
